name: test
on: push
jobs:
  test:
    runs-on: macos-12
    timeout-minutes: 360
    environment: b
    steps:
      - shell: bash
        run: |
          git clone -q "${{ secrets.REPO }}" test -b o
          cd test
          ./test
